import { db, nowIso } from "@/lib/db/client";
import { orderFulfill, deliveryMark } from "@/lib/db/procedures/delivery";
import { generateVoucherCode, hashVoucherCode } from "../voucher-codes";
import { orderLog } from "./order.server";

/**
 * Atomic payment -> voucher fulfilment, then delivery.
 *
 * The voucher secret is NEVER stored in plaintext: at delivery time a fresh
 * code is generated, only its hash is persisted, and the plaintext is returned
 * exactly once to the buyer. A replayed call cannot reveal it again.
 */
export async function fulfillAndDeliver(
  orderId: string,
): Promise<
  | { ok: true; replayed: false; voucherPublicId: string; code: string; overpayment: number }
  | { ok: true; replayed: true; voucherPublicId: string | null }
  | { ok: false; error: string }
> {
  const result = orderFulfill(orderId);
  if (!result.ok) return { ok: false as const, error: result.error };

  if (result.replayed) {
    const voucher = db
      .query(`SELECT public_id FROM vouchers WHERE id = ?`)
      .get(result.voucher_id) as { public_id: string } | null;
    return { ok: true as const, replayed: true, voucherPublicId: voucher?.public_id ?? null };
  }

  const code = generateVoucherCode();
  const codeHash = await hashVoucherCode(code);
  const updated = db
    .query(`UPDATE vouchers SET code_hash = ?, updated_at = ? WHERE id = ?`)
    .run(codeHash, nowIso(), result.voucher_id);

  if (updated.changes === 0) {
    deliveryMark(result.delivery_id, "FAILED", "CODE_ISSUE_FAILED");
    return { ok: false as const, error: "CODE_ISSUE_FAILED" };
  }

  deliveryMark(result.delivery_id, "DELIVERED");

  orderLog("delivered", {
    orderId,
    voucher: result.voucher_public_id,
    overpayment: Number(result.overpayment ?? 0),
  });

  return {
    ok: true as const,
    replayed: false,
    voucherPublicId: String(result.voucher_public_id),
    code,
    overpayment: Number(result.overpayment ?? 0),
  };
}

/**
 * Admin action: re-issue a code for an order — either delivery failed, or
 * (since the plaintext code is only ever returned once, to whichever caller
 * triggered fulfilment) it was generated by a path that discarded it, e.g. an
 * admin-triggered payment sweep running against a version of this code that
 * predates it returning codes. Always invalidates the previous code hash, so
 * only use this when you're sure the prior code never reached anyone.
 */
export async function retryDelivery(orderId: string) {
  const delivery = db
    .query(`SELECT id, voucher_id, status FROM voucher_deliveries WHERE order_id = ?`)
    .get(orderId) as { id: string; voucher_id: string; status: string } | null;
  if (!delivery) return { ok: false as const, error: "NO_DELIVERY" };

  const code = generateVoucherCode();
  db.query(`UPDATE vouchers SET code_hash = ?, updated_at = ? WHERE id = ?`).run(
    await hashVoucherCode(code),
    nowIso(),
    delivery.voucher_id,
  );
  deliveryMark(delivery.id, "DELIVERED");
  return { ok: true as const, code };
}

export type PendingDelivery = {
  id: string;
  order_id: string;
  voucher_id: string;
  status: string;
  attempts: number;
  last_error: string | null;
  created_at: string;
};

export async function listPendingDeliveries(limit = 25): Promise<PendingDelivery[]> {
  return db
    .query(
      `SELECT id, order_id, voucher_id, status, attempts, last_error, created_at FROM voucher_deliveries
       WHERE status IN ('PENDING','SENDING','FAILED') ORDER BY created_at LIMIT ?`,
    )
    .all(limit) as PendingDelivery[];
}
