/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedBatchesRouteImport } from './routes/_authenticated/batches'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLedgerRouteImport } from './routes/_authenticated/ledger'
import { Route as AuthenticatedOpsRouteImport } from './routes/_authenticated/ops'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedPayoutsRouteImport } from './routes/_authenticated/payouts'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedVouchersRouteImport } from './routes/_authenticated/vouchers'
import { Route as OrderPublicOrderIdRouteImport } from './routes/order.$publicOrderId'
import { Route as RedeemPublicIdRouteImport } from './routes/redeem.$publicId'
import { Route as ApiPublicCronSweepRouteImport } from './routes/api/public/cron/sweep'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBatchesRoute = AuthenticatedBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLedgerRoute = AuthenticatedLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpsRoute = AuthenticatedOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayoutsRoute = AuthenticatedPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVouchersRoute = AuthenticatedVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OrderPublicOrderIdRoute = OrderPublicOrderIdRouteImport.update({
  id: '/order/$publicOrderId',
  path: '/order/$publicOrderId',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemPublicIdRoute = RedeemPublicIdRouteImport.update({
  id: '/redeem/$publicId',
  path: '/redeem/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronSweepRoute = ApiPublicCronSweepRouteImport.update({
  id: '/api/public/cron/sweep',
  path: '/api/public/cron/sweep',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buy': typeof BuyRoute
  '/account': typeof AuthenticatedAccountRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/batches': typeof AuthenticatedBatchesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/ops': typeof AuthenticatedOpsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/payouts': typeof AuthenticatedPayoutsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/vouchers': typeof AuthenticatedVouchersRoute
  '/order/$publicOrderId': typeof OrderPublicOrderIdRoute
  '/redeem/$publicId': typeof RedeemPublicIdRoute
  '/api/public/cron/sweep': typeof ApiPublicCronSweepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buy': typeof BuyRoute
  '/account': typeof AuthenticatedAccountRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/batches': typeof AuthenticatedBatchesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ledger': typeof AuthenticatedLedgerRoute
  '/ops': typeof AuthenticatedOpsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/payouts': typeof AuthenticatedPayoutsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/vouchers': typeof AuthenticatedVouchersRoute
  '/order/$publicOrderId': typeof OrderPublicOrderIdRoute
  '/redeem/$publicId': typeof RedeemPublicIdRoute
  '/api/public/cron/sweep': typeof ApiPublicCronSweepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/buy': typeof BuyRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/batches': typeof AuthenticatedBatchesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ledger': typeof AuthenticatedLedgerRoute
  '/_authenticated/ops': typeof AuthenticatedOpsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/payouts': typeof AuthenticatedPayoutsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/vouchers': typeof AuthenticatedVouchersRoute
  '/order/$publicOrderId': typeof OrderPublicOrderIdRoute
  '/redeem/$publicId': typeof RedeemPublicIdRoute
  '/api/public/cron/sweep': typeof ApiPublicCronSweepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buy'
    | '/account'
    | '/agent'
    | '/agents'
    | '/audit'
    | '/batches'
    | '/dashboard'
    | '/ledger'
    | '/ops'
    | '/orders'
    | '/payouts'
    | '/transactions'
    | '/vouchers'
    | '/order/$publicOrderId'
    | '/redeem/$publicId'
    | '/api/public/cron/sweep'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buy'
    | '/account'
    | '/agent'
    | '/agents'
    | '/audit'
    | '/batches'
    | '/dashboard'
    | '/ledger'
    | '/ops'
    | '/orders'
    | '/payouts'
    | '/transactions'
    | '/vouchers'
    | '/order/$publicOrderId'
    | '/redeem/$publicId'
    | '/api/public/cron/sweep'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/buy'
    | '/_authenticated/account'
    | '/_authenticated/agent'
    | '/_authenticated/agents'
    | '/_authenticated/audit'
    | '/_authenticated/batches'
    | '/_authenticated/dashboard'
    | '/_authenticated/ledger'
    | '/_authenticated/ops'
    | '/_authenticated/orders'
    | '/_authenticated/payouts'
    | '/_authenticated/transactions'
    | '/_authenticated/vouchers'
    | '/order/$publicOrderId'
    | '/redeem/$publicId'
    | '/api/public/cron/sweep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuyRoute: typeof BuyRoute
  OrderPublicOrderIdRoute: typeof OrderPublicOrderIdRoute
  RedeemPublicIdRoute: typeof RedeemPublicIdRoute
  ApiPublicCronSweepRoute: typeof ApiPublicCronSweepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/batches': {
      id: '/_authenticated/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof AuthenticatedBatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ledger': {
      id: '/_authenticated/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthenticatedLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops': {
      id: '/_authenticated/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof AuthenticatedOpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payouts': {
      id: '/_authenticated/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AuthenticatedPayoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vouchers': {
      id: '/_authenticated/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof AuthenticatedVouchersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/order/$publicOrderId': {
      id: '/order/$publicOrderId'
      path: '/order/$publicOrderId'
      fullPath: '/order/$publicOrderId'
      preLoaderRoute: typeof OrderPublicOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem/$publicId': {
      id: '/redeem/$publicId'
      path: '/redeem/$publicId'
      fullPath: '/redeem/$publicId'
      preLoaderRoute: typeof RedeemPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sweep': {
      id: '/api/public/cron/sweep'
      path: '/api/public/cron/sweep'
      fullPath: '/api/public/cron/sweep'
      preLoaderRoute: typeof ApiPublicCronSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedBatchesRoute: typeof AuthenticatedBatchesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLedgerRoute: typeof AuthenticatedLedgerRoute
  AuthenticatedOpsRoute: typeof AuthenticatedOpsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPayoutsRoute: typeof AuthenticatedPayoutsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedVouchersRoute: typeof AuthenticatedVouchersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedBatchesRoute: AuthenticatedBatchesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLedgerRoute: AuthenticatedLedgerRoute,
  AuthenticatedOpsRoute: AuthenticatedOpsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPayoutsRoute: AuthenticatedPayoutsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedVouchersRoute: AuthenticatedVouchersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuyRoute: BuyRoute,
  OrderPublicOrderIdRoute: OrderPublicOrderIdRoute,
  RedeemPublicIdRoute: RedeemPublicIdRoute,
  ApiPublicCronSweepRoute: ApiPublicCronSweepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
